import { admin, notConfigured } from '../../../../lib/supabaseAdmin.mjs'
import { bump } from '../../../../lib/redis.mjs'
import {
  normalizeCode, isValidCode, isPlayerId, sanitizeText, milliToWei, START_PURSE_MILLI,
} from '../../../../lib/freeRoom.mjs'
import { squadForAddress } from '../../../../lib/tx.mjs'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

/**
 * Join a free room. No wallet, no MON, no account — a name and a face.
 *
 * The player id is generated by the browser and kept in localStorage, so a
 * reload rejoins as the same person. That is a deliberately weak identity: it
 * is a party game with nothing at stake, and the alternative (accounts) is the
 * friction we are trying to avoid. Nothing here can be stolen because nothing
 * here is worth anything.
 */
const MAX_JOINS_PER_MINUTE = 30

export async function POST(request) {
  if (!admin) return notConfigured()

  let body
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'bad request body' }, { status: 400 })
  }

  const code = normalizeCode(body?.code)
  const playerId = String(body?.playerId || '').toLowerCase()
  const name = sanitizeText(body?.name, 40) || null
  const avatarSeed = sanitizeText(body?.avatarSeed, 40) || null

  if (!isValidCode(code)) return Response.json({ error: 'code required' }, { status: 400 })
  if (!isPlayerId(playerId)) return Response.json({ error: 'bad player id' }, { status: 400 })

  const ip = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'local'
  if ((await bump(`free:join:${ip}`, 60)) > MAX_JOINS_PER_MINUTE) {
    return Response.json({ error: 'Slow down a moment.' }, { status: 429 })
  }

  // Logging in is OPTIONAL and only decides whether this room lands in a saved
  // history. The account is resolved from the bearer token by Supabase, never
  // read from the body — a user id in a payload is a claim, not proof.
  let userId = null
  const auth = request.headers.get('authorization') || ''
  if (auth.toLowerCase().startsWith('bearer ')) {
    try {
      const { data } = await admin.auth.getUser(auth.slice(7).trim())
      userId = data?.user?.id ?? null
    } catch {
      // A bad or expired token must not block the join — it only costs history.
      userId = null
    }
  }

  const { data: room } = await admin
    .from('free_rooms').select('mode, closed').eq('code', code).maybeSingle()
  if (!room) return Response.json({ error: 'room not found' }, { status: 404 })
  if (room.closed) return Response.json({ error: 'This room has ended.' }, { status: 409 })

  // Fantasy rooms draft you from your id, exactly as the on-chain rooms draft
  // from a wallet address — letting people pick collapses into one big team.
  const squad = Number(room.mode) === 1 ? squadForAddress(playerId) : null

  const args = {
    p_code: code,
    p_player: playerId,
    p_name: name,
    p_avatar: avatarSeed,
    p_squad: squad,
    p_purse: Number(START_PURSE_MILLI),
  }

  let { data, error } = await admin.rpc('free_join', { ...args, p_user: userId })

  // Migration window: 007 is what teaches free_join about accounts. Until it is
  // applied the 7-argument overload does not exist, and PostgREST answers
  // PGRST202. Falling back to the 6-argument call keeps people able to JOIN —
  // they just don't get history yet, which is the right thing to degrade.
  // Safe to delete once 007 is applied everywhere.
  if (error?.code === 'PGRST202') {
    ;({ data, error } = await admin.rpc('free_join', args))
  }

  if (error) {
    const m = error.message || ''
    // Keep these aligned with the pre-check above and with /api/free/bid: a
    // closed room is a state conflict (409), being removed is an authorisation
    // failure (403). Lumping them together made the same condition answer 409
    // or 403 depending on which path happened to catch it.
    const status =
      /no_room/.test(m) ? 404
      : /room_closed/.test(m) ? 409
      : /kicked/.test(m) ? 403
      : 500
    return Response.json({ error: friendly(m) }, { status })
  }

  const row = Array.isArray(data) ? data[0] : data
  return Response.json({
    saved: Boolean(row.user_id),
    player: {
      addr: row.player_id,
      entityId: row.entity_id,
      name: row.name,
      avatarSeed: row.avatar_seed,
      squad: row.squad,
      purse: milliToWei(row.purse),
      spent: milliToWei(row.spent),
    },
  })
}

const friendly = (m) => {
  if (/no_room/.test(m)) return 'That room no longer exists.'
  if (/room_closed/.test(m)) return 'This auction has already ended.'
  // A removed player must not be able to walk back in by refreshing.
  if (/kicked/.test(m)) return 'The host removed you from this room.'
  return 'Could not join this room.'
}
