import { admin, notConfigured } from '../../../../lib/supabaseAdmin.mjs'
import { bump } from '../../../../lib/redis.mjs'
import {
  normalizeCode, isValidCode, isPlayerId, sanitizeText, milliToWei, START_PURSE_MILLI,
} from '../../../../lib/freeRoom.mjs'
import { squadForAddress } from '../../../../lib/tx.mjs'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

/**
 * Join a free room. No wallet, no MON, no account — a name and a face.
 *
 * The player id is generated by the browser and kept in localStorage, so a
 * reload rejoins as the same person. That is a deliberately weak identity: it
 * is a party game with nothing at stake, and the alternative (accounts) is the
 * friction we are trying to avoid. Nothing here can be stolen because nothing
 * here is worth anything.
 */
const MAX_JOINS_PER_MINUTE = 30

export async function POST(request) {
  if (!admin) return notConfigured()

  let body
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'bad request body' }, { status: 400 })
  }

  const code = normalizeCode(body?.code)
  const playerId = String(body?.playerId || '').toLowerCase()
  const name = sanitizeText(body?.name, 40) || null
  const avatarSeed = sanitizeText(body?.avatarSeed, 40) || null

  if (!isValidCode(code)) return Response.json({ error: 'code required' }, { status: 400 })
  if (!isPlayerId(playerId)) return Response.json({ error: 'bad player id' }, { status: 400 })

  const ip = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'local'
  if ((await bump(`free:join:${ip}`, 60)) > MAX_JOINS_PER_MINUTE) {
    return Response.json({ error: 'Slow down a moment.' }, { status: 429 })
  }

  const { data: room } = await admin
    .from('free_rooms').select('mode, closed').eq('code', code).maybeSingle()
  if (!room) return Response.json({ error: 'room not found' }, { status: 404 })
  if (room.closed) return Response.json({ error: 'This room has ended.' }, { status: 409 })

  // Fantasy rooms draft you from your id, exactly as the on-chain rooms draft
  // from a wallet address — letting people pick collapses into one big team.
  const squad = Number(room.mode) === 1 ? squadForAddress(playerId) : null

  const { data, error } = await admin.rpc('free_join', {
    p_code: code,
    p_player: playerId,
    p_name: name,
    p_avatar: avatarSeed,
    p_squad: squad,
    p_purse: Number(START_PURSE_MILLI),
  })

  if (error) {
    const m = error.message || ''
    const status = /no_room/.test(m) ? 404 : /kicked|room_closed/.test(m) ? 403 : 500
    return Response.json({ error: friendly(m) }, { status })
  }

  const row = Array.isArray(data) ? data[0] : data
  return Response.json({
    player: {
      addr: row.player_id,
      entityId: row.entity_id,
      name: row.name,
      avatarSeed: row.avatar_seed,
      squad: row.squad,
      purse: milliToWei(row.purse),
      spent: milliToWei(row.spent),
    },
  })
}

const friendly = (m) => {
  if (/no_room/.test(m)) return 'That room no longer exists.'
  if (/room_closed/.test(m)) return 'This auction has already ended.'
  // A removed player must not be able to walk back in by refreshing.
  if (/kicked/.test(m)) return 'The host removed you from this room.'
  return 'Could not join this room.'
}
