/**
 * solc-js standard-JSON compile. No Foundry, no Hardhat, no install risk.
 *
 * Two settings here are load-bearing and easy to omit in a hand-rolled script:
 *   evmVersion: 'cancun'  — a fork mismatch surfaces as an inscrutable invalid
 *                           opcode at deploy time, typically hours later.
 *   optimizer enabled     — roughly 30% of deploy cost, which is real MON.
 */
import solc from 'solc'
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, join } from 'node:path'

const CONTRACTS = resolve(process.cwd(), 'contracts')
const ARTIFACTS = resolve(process.cwd(), 'artifacts')

const only = process.argv[2]
const files = readdirSync(CONTRACTS).filter(
  (f) => f.endsWith('.sol') && (!only || f === `${only}.sol`),
)

if (!files.length) {
  console.error(`\n  No contracts found${only ? ` matching "${only}"` : ''} in contracts/\n`)
  process.exit(1)
}

const input = {
  language: 'Solidity',
  sources: Object.fromEntries(
    files.map((f) => [f, { content: readFileSync(join(CONTRACTS, f), 'utf8') }]),
  ),
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'cancun',
    outputSelection: {
      '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object', 'metadata'] },
    },
  },
}

const out = JSON.parse(solc.compile(JSON.stringify(input)))

const errors = (out.errors ?? []).filter((e) => e.severity === 'error')
const warnings = (out.errors ?? []).filter((e) => e.severity === 'warning')

for (const w of warnings) console.warn(`  warning: ${w.formattedMessage.trim()}`)
if (errors.length) {
  console.error()
  for (const e of errors) console.error(e.formattedMessage)
  process.exit(1)
}

if (!existsSync(ARTIFACTS)) mkdirSync(ARTIFACTS, { recursive: true })

console.log()
for (const [file, contracts] of Object.entries(out.contracts ?? {})) {
  for (const [name, c] of Object.entries(contracts)) {
    const bytecode = `0x${c.evm.bytecode.object}`
    const deployedSize = c.evm.deployedBytecode.object.length / 2
    writeFileSync(
      join(ARTIFACTS, `${name}.json`),
      JSON.stringify({ name, abi: c.abi, bytecode, metadata: c.metadata }, null, 2),
    )
    // Monad's limit is 128KB, far above Ethereum's 24KB — worth knowing, but
    // deploy gas scales with size and that costs real MON.
    console.log(`  ${name.padEnd(12)} ${String(deployedSize).padStart(6)} bytes   artifacts/${name}.json`)

    // artifacts/ is gitignored but Vercel builds from git, so the ABI the app
    // imports has to be a committed source file, not a build output.
    if (name === 'BidBlitz') {
      writeFileSync(
        resolve(process.cwd(), 'src', 'lib', 'abi.mjs'),
        `// GENERATED by scripts/compile.mjs — do not edit by hand.\n` +
          `export const BIDBLITZ_ABI = ${JSON.stringify(c.abi, null, 2)}\n`,
      )
      console.log(`  ${''.padEnd(12)} ${''.padStart(6)}         src/lib/abi.mjs`)
    }
  }
}
console.log(`\n  solc ${solc.version()}\n`)
